import os
import sys

apk = sys.argv[1]

# Cross platform frameworks currently supported
crossPlatfromFrameworks = {'cordova': 'org.apache.cordova', 'adobeAir': 'com.adobe.air', 'titanium': 'org.appcelerator.titanium'}

os.system("java -jar " + "ClassyShark.jar" + " -export " + apk)

textfile = open("all_classes.txt", 'r').read()


def cleanup():
    # Delete the files generated by Classy Shark
    os.remove("all_classes.txt")
    os.remove("all_methods.txt")
    os.remove("all_strings.txt")
    os.remove("method_counts.txt")
    os.remove("AndroidManifest.xml_dump")


for k, v in crossPlatfromFrameworks.items():
    if v in textfile:
        print("This app uses the {var} cross-platform framework".format(var=k))
        cleanup()
        sys.exit(1)
print("This app doesn't use any of the specifed cross platform frameworks")
cleanup()
